### ISSUE TITLE
"Error reading XLS file: Unable to allocate memory"

### ISSUE THREAD

**Issue by Kodiologist** [libxls/libxls#109]
```
$ wget 'https://en.www.inegi.org.mx/contenidos/programas/ccpv/2010/microdatos/iter/ageb_manzana/14_jalisco_2010_ageb_manzana_urbana_xls.zip'
…
$ unzip 14_jalisco_2010_ageb_manzana_urbana_xls.zip
Archive:  14_jalisco_2010_ageb_manzana_urbana_xls.zip
  inflating: RESAGEBURB_14XLS10.xls
$ xls2csv ~/scr/RESAGEBURB_14XLS10.xls
FILE: RESAGEBURB_14XLS10.xls
Error reading XLS file: Unable to allocate memory
```

I'm running this on a machine with about three-quarters of a terabyte of RAM, so I doubt that running out of RAM is the issue.

I'm using libxls 1.6.2 freshly compiled from source.

**Comment by evanmiller** [comment]
Hi, there are some sanity checks in the code to ensure that the library doesn't eat up all of the system RAM with malformed input. One of the checks assumes that the Shared String Table is smaller than 16 MB. This doesn't seem to be the case with the file you provided, so I'll bump that up to 64 MB.
