### ISSUE TITLE
configure fails

### ISSUE THREAD

**Issue by polluks** [libxls/libxls#117]
```
./configure: line 12718: syntax error near unexpected token `,'
./configure: line 12718: `AX_CXX_COMPILE_STDCXX_11(, optional)'

**Comment by evanmiller** [comment]
As mentioned in the readme, you will need to install `autoconf-archive` before running `bootstrap`.

**Comment by emrahayanoglu** [comment]
Experienced the same error on configure, solution proposed bu @evanmiller is confirmed.
So that, I would say that we can close this ticket.

**Comment by polluks** [comment]
thx
