### ISSUE TITLE
Releases 1.6.3？

### ISSUE THREAD

**Issue by ZhangLimengLimeng** [libxls/libxls#123]
I want to use libxls in golang and the golang project in readme is using dev branches.
I have install autoconf-archive, and the error is ./configure: line 16952: syntax error near unexpected token `,'./configure: line 16952: `AX_CXX_COMPILE_STDCXX_11(, optional)'   >_<
maybe there's another wrong in my system.
so could you push an releases package 1.6.3?

**Comment by kloczek** [comment]
+1

**Comment by durrish** [comment]
same problem. did you solve it?

**Comment by evanmiller** [comment]
Done! https://github.com/libxls/libxls/releases/tag/v1.6.3
