### ISSUE TITLE
can't read .xls file on embedded OS(openwrt)

### ISSUE THREAD

**Issue by suonikeyinsuxiao** [libxls/libxls#23]
try to use libxls to read data from Excel file. On ubuntu, it works successfully. But, On Openwrt, it failed.
I have attached the log files on each OS, please help to locate.Thanks
[openwrt.log](https://github.com/evanmiller/libxls/files/2043286/openwrt.log)
[ubuntu.log](https://github.com/evanmiller/libxls/files/2043287/ubuntu.log)

**Comment by evanmiller** [comment]
Possibly fixed in https://github.com/libxls/libxls/commit/284ee9a252e99f1216a4712f18ba04fb2ea1140d

**Comment by evanmiller** [comment]
Closing since there has been no further update from the original reporter.
