### ISSUE TITLE
Line flagged in CRAN's clang-UBSAN checks

### ISSUE THREAD

**Issue by jennybc** [libxls/libxls#46]
readxl currently has a ... memo, I'll call it, from their clang-UBSAN checks. readxl still passes `R CMD check` and our own tests cleanly but this line gets flagged:

https://github.com/libxls/libxls/blob/cef1393eebd6b9a3c360f14c444d8541614cf21c/src/xlstool.c#L622

Here's the detailed report:

https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/readxl/tests/testthat.Rout

~I suspect that this can be seen as a false positive, in light of external knowledge of the xls spec and memory layout.~ I'm trying to figure that out for myself, but would be happy for any wisdom or wording you have to share.

**Comment by jennybc** [comment]
That ⬆️ result pertains to the previous version of readxl and therefore an earlier version of libxls. But this piece of code hasn't changed recently and would be exactly like this in the version of readxl I'm about to submit. Ideally I'll have some comforting words to put in my submission.

**Comment by sjmulder** [comment]
Not wanting to derail the discussion but shouldn’t the `malloc()` return values be checked?

**Comment by evanmiller** [comment]
@jennybc I think casting double to int is undefined in some cases (e.g. NAN).

If it gets flagged we could try

```
                    snprintf(ret, retlen, "%.0f", cell->d);
```

As in a later line. I'm really not sure what this section of code is trying to achieve, I'd have to dig into the spec to find out.

**Comment by evanmiller** [comment]
@sjmulder Yes

**Comment by jennybc** [comment]
> I'm really not sure what this section of code is trying to achieve

So far, I've managed to gather it's for capturing a string representation of numeric cells.

**Comment by jennybc** [comment]
We don't consult the `str` field of, say, a numeric cell, even when we need to convert it to a string in readxl, e.g. a numeric cell in a column we've decided is character. We have our own code for this. If I could trust it, it would be interesting to rely on libxls for this, now that I think about it. Especially if it actually implemented formats (which doesn't seem to be the case now).

**Comment by jennybc** [comment]
If I've understood the goal correctly, here's where we do similar in readxl, in case it's helpful at all.

https://github.com/tidyverse/readxl/blob/454bde1433031261daf4d1c8339954ec30d56f62/src/XlsCell.h#L241-L258

But @evanmiller the workaround you suggest above is probably the right move short-term.
