### ISSUE TITLE
Unnecessary configure checks?

### ISSUE THREAD

**Issue by QuLogic** [libxls/libxls#48]
`configure` appears to check for a C++ compiler, but no C++ code is compiled (though some does exist). It also checks for `pkg-config`, but no dependencies are queried using it.

**Comment by QuLogic** [comment]
`AC_C_CONST` is also obsolescent and should not be used.

**Comment by evanmiller** [comment]
PRs welcome

**Comment by QuLogic** [comment]
Well, I'm not sure about the C++ compiler; are those files supposed to be compiled into something?

**Comment by evanmiller** [comment]
We should probably compile them as part of a test suite (since the library is advertised as having C/C++ support), but right now, they are not compiled.

**Comment by evanmiller** [comment]
Actually, the C++ compiler is used when compiling the fuzzing targets. "make fuzz_xls"

**Comment by QuLogic** [comment]
Ah yes, good point, I was looking for cpp (not cxx) since those were the names of the files.
