### ISSUE TITLE
Unreadable files with, I think, Latin-1 encoded contents

### ISSUE THREAD

**Issue by jennybc** [libxls/libxls#55]
Passing along from readxl https://github.com/tidyverse/readxl/issues/564.

User has 6 xls files, one of which can be read by readxl and xls2csv. The remaining five do not throw an error, but they produce no output. 

I note I *can* read these files with a completely separate tool (the R package gdata, which wraps a Perl script 😬), but only if I specify the encoding: e.g., as `read.xls(files[2], fileEncoding="latin1")`. 

I've attempted to pass encoding to xls2csv but it does not change my results. That could be user error because I've never really specified encoding to libxls before.

I can also confirm what the user reports: merely opening and closing the problematic files in Excel makes them readable by readxl/libxls. I suppose this is changing the encoding?

The attached ZIP file is the one provided by my user in the readxl issue. I contains 6 directories, each of which holds one `.txt` and one `.xls` file.

``` r
fs::dir_tree("investigations/Data")
#> investigations/Data
#> ├── 20190326.seq
#> │   ├── 2019-3-26-.txt
#> │   └── 33.0000.XLS
#> ├── 20190327.seq
#> │   ├── 01.0000.XLS
#> │   └── 2019-3-27-.txt
#> ├── 20190328.seq
#> │   ├── 04.0000.XLS
#> │   └── 2019-3-28-.txt
#> ├── 20190329.seq
#> │   ├── 15.0000.XLS
#> │   └── 2019-3-29-.txt
#> ├── 20190330.seq
#> │   ├── 09.0000.XLS
#> │   └── 2019-3-30-.txt
#> ├── 20190331.seq
#> │   ├── 03.0000.XLS
#> │   └── 2019-3-31-.txt
#> └── Data.Rproj
```

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

[Data.zip](https://github.com/libxls/libxls/files/3034919/Data.zip)

**Comment by jennybc** [comment]
> Are you checking the return values of `xls_parseWorkSheet`?

No, I am apparently not. But I can change that.

https://github.com/tidyverse/readxl/blob/9d665bbb46923281911eddd4531617a461bad645/src/XlsWorkSheet.h#L61

Reading between the lines ... do you believe these files *should* be readable by libxls (+ readxl)? Or will you deem them as invalid or sufficiently peculiar as to be #wontfix?

**Comment by evanmiller** [comment]
> Reading between the lines ... do you believe these files should be readable by libxls (+ readxl)? Or will you deem them as invalid or sufficiently peculiar as to be #wontfix?

I don't have an opinion on that yet.

**Comment by evanmiller** [comment]
Update: libxls currently only supports UTF-16 internally. The issue here is that these files' strings are encoded with CP-936. We have some infrastructure in place for charset conversion (mainly to support various output encodings) but it will take some work to support multiple input encodings.

**Comment by evanmiller** [comment]
I should clarify: *one* issue is the string encoding. There are possibly other issues at play.

**Comment by evanmiller** [comment]
@jennybc It looks like these files have the same issue as #76. Please try the dev branch and let me know if they are now opening for you.

**Comment by evanmiller** [comment]
@jennybc Also please see this pull request for improvements to the character set / code page handling:

https://github.com/libxls/libxls/pull/77

**Comment by evanmiller** [comment]
These files open in libxls 1.5.3. If you are still experiencing issues, please open a new issue.

**Comment by jennybc** [comment]
Thanks for this and the other recent changes. I am working on something else right now but will pull this all in next time I take a pass through readxl. Which should be soon-ish, i.e. within "a couple of months".
