### ISSUE TITLE
Can/does libxls know whether formulas have been evaluated?

### ISSUE THREAD

**Issue by jennybc** [libxls/libxls#57]
I'd appreciate a quick opinion on this:

https://github.com/tidyverse/readxl/issues/565

TL;DR xls file contains formulas that have never been evaluated. How feasible is it to catch that and surface a useful message or error vs returning nothing/emptiness?

**Comment by evanmiller** [comment]
The formula handling code is here:

https://github.com/libxls/libxls/blob/master/src/xls.c#L536

I don't immediately see anything to indicate whether a formula has been evaluated - it's possible this information is stored in `cell->flags`.

**Comment by jennybc** [comment]
OK thanks for link and info.

**Comment by jennybc** [comment]
FWIW I inspected these specific cells in a debugger and they **are** detected as formulas, but as numeric formulas. I did not dig deeply enough to determine why, what should really happen, etc.

My personal assessment is that it's 80% likely to be a deeply weird xls file (this source has previously acknowledged writing xls with a custom sed script), 20% to be an edge case libxls does not account for.
