### ISSUE TITLE
AX_CXX_COMPILE_STDCXX_11 not found

### ISSUE THREAD

**Issue by evanmiller** [libxls/libxls#58]
Not sure what the proper solution is but with the recent C++ changes I get

```
./configure: line 17117: AX_CXX_COMPILE_STDCXX_11: command not found
```

**Comment by evanmiller** [comment]
CC @QuLogic

**Comment by QuLogic** [comment]
You must have autoconf-archive installed before running autoconf, or you can start shipping the file in the repository.

**Comment by evanmiller** [comment]
Thanks
