### ISSUE TITLE
How to get the formula of a cell ?

### ISSUE THREAD

**Issue by sletz** [libxls/libxls#59]
I can parse an xml file with formula like` $C$5*D5`, but can only get the result of the actual computation of the formula, not the formula itself: can the `$C$5*D5` string be retrieved?

**Comment by evanmiller** [comment]
You can access the raw formula bytes by setting a formula handler

```C
typedef void (*xls_formula_handler)(WORD bof, WORD len, BYTE *formula);
void xls_set_formula_hander(xls_formula_handler handler);
```

However, the library does not include any facilities for converting binary formulas into a string.
