### ISSUE TITLE
Cannot read this file with error "Unable to read sector"

### ISSUE THREAD

**Issue by MatthieuTexier** [libxls/libxls#60]
Hello,
I cannot read the attached file.
I didn't find anything weird in it.

last errors are:
Error: fread wanted 1 got 0 loc=16896
Error: Unable to read sector #32
Error: failed to read OLE block

I had to rename the file as .txt to import it :-(
[NO-BAT035A-00.txt](https://github.com/libxls/libxls/files/3252365/NO-BAT035A-00.txt)

Thanks for your help.

**Comment by MatthieuTexier** [comment]
Can anybody help ?
Thank

**Comment by evanmiller** [comment]
Hi,

Please test with the latest version of libxls. This file is opening fine on my machine.

If you are still experiencing problems, please include details about your platform (operating system and compiler).

**Comment by MatthieuTexier** [comment]
Thank you for your help.
I did try with the latest sources and compiler, and still have the same problem.
[resuts.txt](https://github.com/libxls/libxls/files/4764328/resuts.txt)

Configuration:
C compiler: gcc
C++ compiler: g++
CFLAGS: -g -O2
CXXFLAGS: -g -O2
LIBS:  
Host: x86_64-pc-linux-gnu
Extra ld flags: 
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by evanmiller** [comment]
Can you please try with the "dev" branch?

https://github.com/libxls/libxls/tree/dev

Thanks

**Comment by MatthieuTexier** [comment]
sure.
It's working fine on branch dev :-)
[results.txt](https://github.com/libxls/libxls/files/4764950/results.txt)

**Comment by evanmiller** [comment]
Merged fix into master branch, closing issue.
