### ISSUE TITLE
How to extract formatted number?

### ISSUE THREAD

**Issue by shashi4u** [libxls/libxls#71]
Hi,
How can I extract a number formatted like a phone number / currency / percentage / date?
One example is a phone number "(123) 456-7890".
When I tried to extract the number using the code provided in xls2csv, it is returned as "1234567890".
How ever I want to extract it as "(123) 456-7890".

I tried to use the "str" property of the cell_data struct. Unfortunately it stored as "1234567890.0000000"

Can you provide me steps on how to do that?

Thanks.

**Comment by evanmiller** [comment]
Hi, thanks for your interest in the library. However, number formatting is outside the scope of libxls.
