### ISSUE TITLE
less than vs. less or equal: work_sheet->rows.lastrow

### ISSUE THREAD

**Issue by ggcespia** [libxls/libxls#73]
Shouldn't the below line be changed to be strictly less than the rows.lastrow?  If you do <= work_sheet->rows.lastrow then there is always a 'blank' column at the end of each line.

for (int j=0; j<=work_sheet->rows.lastrow; j++) { // rows

**Comment by evanmiller** [comment]
Hi, thanks for the note. It appears there is an internal logic error in the library that is adding an extra column. From the MS-XLS document about the `ROW` record:

> colMac (2 bytes): An unsigned integer that specifies the **one-based index of the last column** that contains a cell populated with data or formatting in the current row. MUST be less than or equal to 256. If colMac is equal to colMic, this record specifies a row with no CELL records.

Curiously, the `ROW` record uses a 1-based index whereas the rest of the file format uses a 0-based index when referencing columns. I'll get this fixed soon.
