### ISSUE TITLE
Libxls 1.6.1 is not working for me anyway

### ISSUE THREAD

**Issue by abcdef123ghi** [libxls/libxls#89]
I tried the the code below on Windows,libxls was not working for me ,it's crashed in the 2nd round of for loop ,and I have no idea ,
the library was built with MSYS2 latest version,it has everything required which mingw gcc g++ libiconv etc
 

    #include "stdafx.h"
    #include <stdlib.h>
    #include <string.h>
    #include <cctype>
    #include <string>
    #include <iostream>
    #include <ctime>
    #include <fstream>
    #include <sstream>

    #include "xls.h"

    using namespace std;
    using namespace xls;

      bool is_number(const string& s)
     {
	   string::const_iterator it = s.begin();
	   while (it != s.end() && isdigit(*it)) ++it;
	   return !s.empty() && it == s.end();
      }

       void write_text_to_log_file(const string &text)
     {
	    ofstream log_file(
		"mt_excel_log.txt", ios_base::out | ios_base::app);

	char * buffer = new char[80];
	time_t time_create = time(NULL);
	struct tm time_info;
	localtime_s(&time_info, &time_create);

	strftime(buffer, 80, "%Y-%m-%d %H:%M:%S", &time_info);
	puts(buffer);

	log_file << text;
	log_file << buffer << endl;
      }

        int readmtexcel(const char * path, char ** barcode, char ** prodno, int * controllmark, int recordscount)
      {

	xls_error_t error = LIBXLS_OK;
	xlsWorkBook *wb = xls_open_file(path, "UTF-8", &error);
	if (wb == NULL) {
		//  printf("Error reading file: %s\n", xls_getError(error));
		string errmsg = "read excel error";
		errmsg = errmsg + xls_getError(error);
		write_text_to_log_file(errmsg);
		return -1;
	}
	//for (int i=0; i<wb->sheets.count; i++) { // sheets
	xlsWorkSheet *work_sheet = xls_getWorkSheet(wb, 0);
	 
	 
	error = xls_parseWorkSheet(work_sheet);
	recordscount = 0;
	for (int j = 1; j <= work_sheet->rows.lastrow; j++) { // rows
		xlsRow *row = xls_row(work_sheet, j);
		// for (int k=0; k<=work_sheet->rows.lastcol; k++) { // columns
		int k = 0;
		xlsCell *cell = &row->cells.cell[k]; // **CRASHED here in the 2nd round of for loop**
		// do something with cell
		if (cell->id == XLS_RECORD_BLANK) {
			// do something with a blank cell
			break;
		}
		else if (cell->id == XLS_RECORD_NUMBER) {
			// use cell->d, a double-precision number
			int barcodenum = cell->d;
			stringstream ss;
			ss << barcodenum;
			string barcodestr = ss.str();
			size_t mysize = barcodestr.length() + 1;
			strcpy_s(barcode[recordscount], mysize, barcodestr.c_str());

		}
		else if (cell->str != NULL) {
			// cell->str contains a string value
			string barcodestr = cell->str;
			size_t mysize = barcodestr.length() + 1;
			strcpy_s(barcode[recordscount], mysize, barcodestr.c_str());

		}
		else{

			break;
		}

		k = 1;
		cell = &row->cells.cell[k];

		if (cell->id == XLS_RECORD_BLANK) {
			// do something with a blank cell
			break;
		}
		else if (cell->id == XLS_RECORD_NUMBER) {
			// use cell->d, a double-precision number
			int prodnonum = cell->d;
			stringstream ss;
			ss << prodnonum;
			string prodnostr = ss.str();
			size_t mysize = prodnostr.length() + 1;
			strcpy_s(prodno[recordscount], mysize, prodnostr.c_str());

		}
		else if (cell->str != NULL) {
			// cell->str contains a string value
			string prodnostr = cell->str;
			size_t mysize = prodnostr.length() + 1;
			strcpy_s(prodno[recordscount], mysize, prodnostr.c_str());

		}
		else{

			break;
		}

		k = 2;
		cell = &row->cells.cell[k];

		if (cell->id == XLS_RECORD_BLANK) {
			// do something with a blank cell
			controllmark[recordscount] = -1;
		}
		else if (cell->id == XLS_RECORD_NUMBER) {
			// use cell->d, a double-precision number
			controllmark[recordscount] = cell->d;

		}
		else if (cell->str != NULL) {
			// cell->str contains a string value
			//  string controllstr=cell->str;
			//  size_t mysize=controllstr.length()+1;
			// strcpy_s(prodno[recordscount],mysize,controllstr.c_str());
			string controllstr = cell->str;
			bool mynumb = is_number(controllstr);
			if (mynumb)
			{
				controllmark[recordscount] = stoi(controllstr);

			}
			else
			{
				controllmark[recordscount] = -2;
			}

		}
		else{

			controllmark[recordscount] = -3;
		}

		recordscount++;

		// }
		//}
		xls_close_WS(work_sheet);
	}
	   xls_close_WB(wb);
	   return 0;
       }

        int _tmain(int argc, _TCHAR* argv[])
     {
	char ** barcode = new char *[10000];
	char ** prodno = new char *[10000];
	int * controllmark = new int[10000];
	int recordscount = 0;

	for (int i = 0; i<10000; i++)
	{
		barcode[i] = new char[20];
		prodno[i] = new char[10];
		controllmark[i] = 0;
	}

	const char * path = "D:\\opensourcelibrary\\CPP\\msys64\\home\\redmond\\mtml20201127.xls";

	int result = readmtexcel(path, barcode, prodno, controllmark, recordscount);

	for (int i = 0; i<recordscount; i++)
	{
		cout << "bardcode:";
		cout << barcode[i];
		cout << "prodno:";
		cout << prodno[i];
		cout << "controllmark:";
		cout << controllmark[i] << endl;
	}
	return 0;
     }

and I thought it might be the way which how to build the library on windows has problem,and I tried to build this program on a Linux machine which is Ubuntu 20.04 with g++,I just found some codes needs to be modified if I have to works on Linux,and I modified some code like strcpy_s  to strcpy,the code below

     #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <cctype>
    #include <string>
    #include <iostream>
    #include <fstream>
    #include <sstream>
    #include <string.h>
    #include <time.h>
    #include "xls.h"

    using namespace std;
    using namespace xls;

     bool is_number(const string& s)
     {
	  string::const_iterator it = s.begin();
	  while (it != s.end() && isdigit(*it)) ++it;
	  return !s.empty() && it == s.end();
    }
     /*
     void write_text_to_log_file(const string &text)
     {
	    ofstream log_file(
		"mt_excel_log.txt", ios_base::out | ios_base::app);

	char * buffer = new char[80];
	time_t time_create = time(NULL);
	struct tm time_info;
	localtime_s(&time_info, &time_create);

	strftime(buffer, 80, "%Y-%m-%d %H:%M:%S", &time_info);
	puts(buffer);

	log_file << text;
	log_file << buffer << endl;
     }
      */
     int readmtexcel(const char * path, char ** barcode, char ** prodno, int * controllmark, int recordscount)
      {

	xls_error_t error = LIBXLS_OK;
	xlsWorkBook *wb = xls_open_file(path, "UTF-8", &error);
	if (wb == NULL) {
		 printf("Error reading file: %s\n", xls_getError(error));
		//string errmsg = "read excel error";
	//	errmsg = errmsg + xls_getError(error);
	   //	write_text_to_log_file(errmsg);
		return -1;
	}
	//for (int i=0; i<wb->sheets.count; i++) { // sheets
	xlsWorkSheet *work_sheet = xls_getWorkSheet(wb, 0);
	 
	 
	error = xls_parseWorkSheet(work_sheet);
	recordscount = 0;
	for (int j = 1; j <= work_sheet->rows.lastrow; j++) { // rows
		xlsRow *row = xls_row(work_sheet, j);
		// for (int k=0; k<=work_sheet->rows.lastcol; k++) { // columns
		int k = 0;
		xlsCell *cell = &row->cells.cell[k];
		// do something with cell
		if (cell->id == XLS_RECORD_BLANK) {
			// do something with a blank cell
			break;
		}
		else if (cell->id == XLS_RECORD_NUMBER) {
			// use cell->d, a double-precision number
			int barcodenum = cell->d;
			stringstream ss;
			ss << barcodenum;
			string barcodestr = ss.str();
			size_t mysize = barcodestr.length() + 1;
		    //	strcpy_s(barcode[recordscount], mysize, barcodestr.c_str());
			strcpy(barcode[recordscount], barcodestr.c_str());

		}
		else if (cell->str != NULL) {
			// cell->str contains a string value
			string barcodestr = cell->str;
			size_t mysize = barcodestr.length() + 1;
			//strcpy_s(barcode[recordscount], mysize, barcodestr.c_str());
			strcpy(barcode[recordscount], barcodestr.c_str());

		}
		else{

			break;
		}

		k = 1;
		cell = &row->cells.cell[k];

		if (cell->id == XLS_RECORD_BLANK) {
			// do something with a blank cell
			break;
		}
		else if (cell->id == XLS_RECORD_NUMBER) {
			// use cell->d, a double-precision number
			int prodnonum = cell->d;
			stringstream ss;
			ss << prodnonum;
			string prodnostr = ss.str();
			size_t mysize = prodnostr.length() + 1;
			//strcpy_s(prodno[recordscount], mysize, prodnostr.c_str());
			strcpy(prodno[recordscount], prodnostr.c_str());

		}
		else if (cell->str != NULL) {
			// cell->str contains a string value
			string prodnostr = cell->str;
			size_t mysize = prodnostr.length() + 1;
			//strcpy_s(prodno[recordscount], mysize, prodnostr.c_str());
			strcpy(prodno[recordscount], prodnostr.c_str());

		}
		else{

			break;
		}

		k = 2;
		cell = &row->cells.cell[k];

		if (cell->id == XLS_RECORD_BLANK) {
			// do something with a blank cell
			controllmark[recordscount] = -1;
		}
		else if (cell->id == XLS_RECORD_NUMBER) {
			// use cell->d, a double-precision number
			controllmark[recordscount] = cell->d;

		}
		else if (cell->str != NULL) {
			// cell->str contains a string value
			//  string controllstr=cell->str;
			//  size_t mysize=controllstr.length()+1;
			// strcpy_s(prodno[recordscount],mysize,controllstr.c_str());
			string controllstr = cell->str;
			bool mynumb = is_number(controllstr);
			if (mynumb)
			{
				controllmark[recordscount] = stoi(controllstr);

			}
			else
			{
				controllmark[recordscount] = -2;
			}

		}
		else{

			controllmark[recordscount] = -3;
		}

		recordscount++;

		// }
		//}
		xls_close_WS(work_sheet);
	}
	xls_close_WB(wb);
	return 0;
    }

    int main()
    {
	char ** barcode = new char *[10000];
	char ** prodno = new char *[10000];
	int * controllmark = new int[10000];
	int recordscount = 0;

	for (int i = 0; i<10000; i++)
	{
		barcode[i] = new char[20];
		prodno[i] = new char[10];
		controllmark[i] = 0;
	}

	const char * path =  "/home/developer/mtml20201127.xls";

	int result = readmtexcel(path, barcode, prodno, controllmark, recordscount);

	for (int i = 0; i<recordscount; i++)
	{
		cout << "bardcode:";
		cout << barcode[i];
		cout << "prodno:";
		cout << prodno[i];
		cout << "controllmark:";
		cout << controllmark[i] << endl;
	}

    /*	for (int i = 0; i<10000; i++)
	{
		delete barcode[i][];
		delete prodno[i][] ;
		
	}
	delete barcode[];
	delete prodno[];
	delete  controllmark[]; */
	system("pause");
	return 0;
    }

I built this programe eventually, but unfortunately it doesn't work as well ,it occured the exception says: free(): double free detected in tcache 2 ,and I just have no idea,I'm really new to Linux,I have no idea how to debug program on Linux,any idea?thank you so much

**Comment by evanmiller** [comment]
Hi, your example is too long to expect anyone to debug. If you have found a specific bug in the library, please post a small test program. Otherwise I recommend posting your problem to StackOverflow where people will be in a better position to help.

**Comment by abcdef123ghi** [comment]
> Hi, your example is too long to expect anyone to debug. If you have found a specific bug in the library, please post a small test program. Otherwise I recommend posting your problem to StackOverflow where people will be in a better position to help.

Thanks for replying, I was not trying to expect someone to debug though,all I trying was hopefully someone to find what wrong I had done,my code was totally imitating from the example, I tried the release of libxls within msys2 on windows and even tried the code on Linux as well,unfortunately it doesn't work,afterward nobody replied me,and I tried freexl library,it works,and I no more used libxls,anyway thanks for the replying
