### ISSUE TITLE
Cross-compilation to i686-w64-mingw32

### ISSUE THREAD

**Issue by vpaesa** [libxls/libxls#98]
Hi,
I configured for cross-.compiling:
`./configure --enable-static --host i686-w64-mingw32`

But I got this error in make:
```
src/.libs/libxlsreader_la-xlstool.o: In function `unicode_decode_wcstombs':
/home/hijico/src/libxls/src/xlstool.c:262: undefined reference to `rpl_malloc'
```
I found an explanation here:
[https://github.com/openvenues/libpostal/issues/134](url)

So I made this small modification in configure.ac:
```
diff --git a/configure.ac b/configure.ac
index 5fa92a7..af2f3b0 100644
--- a/configure.ac
+++ b/configure.ac
@@ -46,10 +46,8 @@ AS_IF([test "x$HAVE_CXX11" != x1], [
 ])
 AM_CONDITIONAL([HAVE_CXX11], [test x$HAVE_CXX11 = x1])
 
-AC_CHECK_FUNCS([strdup wcstombs_l])
+AC_CHECK_FUNCS([malloc realloc strdup wcstombs_l])
 AC_CHECK_HEADERS([wchar.h xlocale.h])
-AC_FUNC_MALLOC
-AC_FUNC_REALLOC
 AC_TYPE_SIZE_T
 
 AC_ARG_ENABLE([fuzz-testing], AS_HELP_STRING([--enable-fuzz-testing], ["Enable fuzz testing (requires Clang 6 or later)"]), [
```
After that (plus bootstrap+configure), my make succeeded.

May you please consider applying that configure.ac modification? 
Thanks in advance.

**Comment by evanmiller** [comment]
Thanks for the report. `AC_FUNC_MALLOC` and `AC_FUNC_REALLOC` substitute their own implementations when the system version returns NULL for zero sizes. I'm honestly not sure whether the library relies on this behavior or not, and clearly it's broken for cross-compiles. I'll remove these functions from the `dev` branch and see if the fuzzer complains.
